<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [8]:
%%sql
select
  p.categoryname,
  PERCENTILE_CONT(.5) within group (order by (case when s.orderdate between '2022-1-1' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate end)) AS y2022_medain_salary,
  PERCENTILE_CONT(.5) within group (order by (case when s.orderdate between '2023-1-1' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate end)) AS y2023_medain_salary
from
  sales s
left join product p on s.productkey = p.productkey
group by
  categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  y2022_medain_salary  y2023_medain_salary
0                          Audio               257.21               266.59
1        Cameras and camcorders                651.46               672.60
2                    Cell phones               418.60               375.88
3                      Computers               809.70               657.18
4                 Games and Toys                33.78                32.62
5                Home Appliances               791.00               825.25
6  Music, Movies and Audio Books               186.58               159.63
7                   TV and Video               730.46               790.79

In [17]:
%%sql

select
  orderdate,
  quantity,
  netprice,
  case
    when quantity >= 2 and netprice >= 100 then 'Multiple Haigh value order'
    when netprice >= 100 then 'Single high value item'
    when quantity >=2 then 'Multiple standard item'
    else 'Single Standard item'
    end as order_type
from sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                  order_type
0  2015-01-01         1     98.97        Single Standard item
1  2015-01-01         1    659.78      Single high value item
2  2015-01-01         2     54.38      Multiple standard item
3  2015-01-01         4    286.69  Multiple Haigh value order
4  2015-01-01         7    135.75  Multiple Haigh value order
5  2015-01-01         3    434.30  Multiple Haigh value order
6  2015-01-01         1     58.73        Single Standard item
7  2015-01-01         3     74.99      Multiple standard item
8  2015-01-01         2    113.57  Multiple Haigh value order
9  2015-01-01         1    499.45      Single high value item

In [28]:
%%sql

select
  p.categoryname,
  sum(case when (s.quantity * s.netprice * s.exchangerate) < 398
    and s.orderdate between '2022-1-1' and '2022-12-31'
  then (s.quantity * s.netprice * s.exchangerate) end) as low_net_revenu_2022,
  sum(case when (s.quantity * s.netprice * s.exchangerate) >= 398
    and s.orderdate between '2022-1-1' and '2022-12-31'
  then (s.quantity * s.netprice * s.exchangerate) end) as high_net_revenu_2022,
  sum(case when (s.quantity * s.netprice * s.exchangerate) < 398
    and s.orderdate between '2023-1-1' and '2023-12-31'
  then (s.quantity * s.netprice * s.exchangerate) end) as low_net_revenu_2023,
  sum(case when (s.quantity * s.netprice * s.exchangerate) >= 398
    and s.orderdate between '2023-1-1' and '2023-12-31'
  then (s.quantity * s.netprice * s.exchangerate) end) as high_net_revenu_2023

  from
    sales s
    left join product p on s.productkey = p.productkey
  group by
    p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,low_net_revenu_2022,high_net_revenu_2022,low_net_revenu_2023,high_net_revenu_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5272448.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4247902.87